### ISSUE TITLE
Confirmation Required

### ISSUE THREAD

**Issue by Philippaul** [CalamariFritti/webDoc2021#2]
Dear Client @CalamariFritti ,
    We have made the index of your website and would like for your conformation to proceed further. We would also like to know about any corrections or disagreement you have in this site to be notified to us, so that it would be easy on both the sites. Thanks in advance.

**Comment by CalamariFritti** [comment]
Hello,

I just read your comment and will have a look at the once I am back in the "office". I will have an answer for you at latest tonight (although it might get rather late).
Thank you, best regards

**Comment by CalamariFritti** [comment]
Ok, so I had a quick glance and the page is looking good! 
Colours and overall structure are really nice. I like the symbols for social media in the header section. Good Job!
I tried with firefox and chromium browser, but apparently the video will not play? 
I am not sure what the problem is here, though. See also attached screenshot. there is only the black area loading with a play button, etc. but nothing happens?

The contact in the lower section is also a nice feature! But when i hit the submit button nothing happens (yet?)

Another minor thing: the main 'headline' (company name in the header) is a bit small? is that on purpose? (see also in the screenshot) looks a bit off, especially compared to the big logo.

Ok, that's it for now. Looking forward to see the rest, thanks again guys and have an good day!

**Comment by Philippaul** [comment]
Dear client,
    Thanks for your feedback. We will address your query in the following
1. Thanks for the matter of video, we will rectify it soon.
2. Th contact form sits ideal without any effect since it is not connected to any database. Having a database is beyond the scope of this course but any way we would love to add if you wish.
3. Thanks for your interest in enlarging the company icon. We will update and notify you soon.

Until then have a nice weekend!
